PRAGMA foreign_keys=OFF;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS template;
DROP TABLE IF EXISTS obstacle;
DROP TABLE IF EXISTS leaderboard;
DROP TABLE IF EXISTS doctrine_migration_versions;
DROP TABLE IF EXISTS messenger_messages;
BEGIN TRANSACTION;
CREATE TABLE doctrine_migration_versions (version VARCHAR(191) NOT NULL, executed_at DATETIME DEFAULT NULL, execution_time INTEGER DEFAULT NULL, PRIMARY KEY(version));
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230504131622','2023-05-04 13:17:08',5);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230524125627','2023-05-24 12:57:30',3);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230524134923','2023-05-24 13:55:36',2);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230524135720','2023-05-24 13:58:34',2);
INSERT INTO doctrine_migration_versions VALUES('DoctrineMigrations\Version20230525064818','2023-05-25 06:48:31',3);
CREATE TABLE book (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(255) NOT NULL, isbn VARCHAR(255) DEFAULT NULL, author VARCHAR(255) NOT NULL, image_url VARCHAR(255) DEFAULT NULL);
INSERT INTO book VALUES(4,'Korea: A Very Short Introduction','9780198830771','Michael J. Seth','https://m.media-amazon.com/images/I/41f3yQct+VL._SX317_BO1,204,203,200_.jpg');
INSERT INTO book VALUES(5,'The Gate to China: A New History of the People''s Republic and Hong Kong','9780197576250','Michael Sheridan','https://m.media-amazon.com/images/I/51AAE2lu9mL._SX424_BO1,204,203,200_.jpg');
INSERT INTO book VALUES(6,'The Marshall Plan: Dawn of the Cold War','978-1501102387','Benn Steil','https://m.media-amazon.com/images/I/41oY9B9ulNL._SX331_BO1,204,203,200_.jpg');
CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL);
CREATE TABLE obstacle (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, difficulty_int INTEGER DEFAULT NULL, difficulty_str INTEGER DEFAULT NULL, difficulty_dex INTEGER DEFAULT NULL, cost_reward_time INTEGER NOT NULL, cost_reward_health INTEGER NOT NULL, cost_reward_stamina INTEGER NOT NULL, cost_reward_int INTEGER NOT NULL, cost_reward_str INTEGER NOT NULL, cost_reward_dex INTEGER NOT NULL, cost_reward_lck INTEGER NOT NULL, cost_reward_spd INTEGER NOT NULL, cost_reward_con INTEGER NOT NULL);
INSERT INTO obstacle VALUES(2,'Blåbärssoppa','Stanna och drick lite blåbärssoppa.',NULL,NULL,NULL,-5,5,15,0,0,0,0,0,3);
INSERT INTO obstacle VALUES(3,'Sandlåda','Du kan fylla på sand i ditt timglas.',NULL,NULL,NULL,20,0,0,1,0,0,0,0,3);
INSERT INTO obstacle VALUES(4,'Yogamatta','Det ligger en yogamatta på vägen! Yoga är bra för hälsan.',NULL,NULL,NULL,-10,35,-10,0,1,1,0,-1,0);
INSERT INTO obstacle VALUES(5,'Fyrklöver','Här ligger en fyrklöver. Vilken tur!',NULL,NULL,NULL,-2,0,0,0,0,0,10,0,0);
INSERT INTO obstacle VALUES(6,'Nya skor','Ett par sprillans nya Nike. Ser snabba ut.',NULL,NULL,NULL,-3,0,0,0,0,2,0,4,1);
INSERT INTO obstacle VALUES(9,'Klättervägg','Klättra över den.',NULL,NULL,61,-6,-1,-12,0,1,3,0,0,1);
INSERT INTO obstacle VALUES(11,'Slagsmål','En våldsam nazist står i din väg och ser hotfull ut.',NULL,NULL,50,-5,-30,-10,0,7,0,2,0,2);
INSERT INTO obstacle VALUES(13,'Kvicksand','Är det lika farligt som i barnprogram? Dags att ta reda på.',NULL,NULL,20,-20,0,-5,1,1,0,0,-1,1);
INSERT INTO obstacle VALUES(14,'Läxa','Åh nej, inte en läxa!',39,NULL,NULL,-5,0,2,4,0,0,0,0,0);
INSERT INTO obstacle VALUES(15,'Fader Fouras','Världens mest kända gåtmästare bor högst upp i ett torn.',99,NULL,NULL,-19,0,-7,7,1,1,0,1,1);
INSERT INTO obstacle VALUES(16,'Gym','Vägen går genom ett gym.',NULL,35,81,-2,0,-11,0,4,1,0,1,4);
INSERT INTO obstacle VALUES(17,'Vilsen hund','Det står en vilsen hund på vägen, den behöver hjälp att hitta sin människa.',45,NULL,18,-13,0,-1,0,0,0,1,0,0);
INSERT INTO obstacle VALUES(18,'Stege','Vägen går under en stege. Du vet vad det betyder.',NULL,NULL,NULL,-1,0,-1,0,0,0,-3,0,0);
INSERT INTO obstacle VALUES(19,'Buske','En snårig buske.',NULL,NULL,18,-6,-5,-4,0,0,0,0,0,1);
INSERT INTO obstacle VALUES(20,'Grind','Grinden är låst. Det måste finnas en nyckel här nånstans.',76,NULL,NULL,-20,0,0,3,0,0,0,0,0);
INSERT INTO obstacle VALUES(21,'Bilväg','Vägen korsar en bilväg. Som tur är finns det ett övergångsställe, bästa att kolla åt båda hållen först.',1,NULL,NULL,-1,0,0,1,0,0,0,0,0);
INSERT INTO obstacle VALUES(22,'Stor sten','En stor sten blockerar vägen. Och en stock också. Du måste flytta på båda för att komma vidare.',NULL,60,NULL,-9,0,-10,0,3,1,0,0,1);
INSERT INTO obstacle VALUES(23,'Trång passage','Vägen går genom en trång passage.',NULL,NULL,9,-3,0,-2,0,0,1,0,0,0);
INSERT INTO obstacle VALUES(25,'Uppförsbacke','En brant uppförsbacke.',NULL,40,40,-4,0,-8,0,1,0,0,0,2);
INSERT INTO obstacle VALUES(26,'Nedförsbacke','Weeeee!',NULL,NULL,5,1,0,0,0,0,0,0,2,0);
INSERT INTO obstacle VALUES(27,'Träsk','Vägen går genom ett kallt, blött och slemmigt träsk. Usch!',NULL,NULL,50,-8,-4,-1,0,0,0,0,-1,0);
INSERT INTO obstacle VALUES(31,'Löpband','Ett löpband står i din väg. Det finns bara ett sätt att ta sig förbi.',NULL,11,41,-5,0,-10,0,2,3,0,1,5);
CREATE TABLE template (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL);
INSERT INTO template VALUES(1,'Jens');
INSERT INTO template VALUES(2,'Stina-Janne');
INSERT INTO template VALUES(3,'Chad');
INSERT INTO template VALUES(4,'Frodo');
INSERT INTO template VALUES(5,'Koriander');
INSERT INTO template VALUES(8,'Jensina');
INSERT INTO template VALUES(9,'Lavera');
CREATE TABLE leaderboard (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, player VARCHAR(255) NOT NULL, challenger VARCHAR(255) NOT NULL, distance INTEGER NOT NULL);
INSERT INTO leaderboard VALUES(1,'Adam','Jens',90);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('book',9);
INSERT INTO sqlite_sequence VALUES('obstacle',31);
INSERT INTO sqlite_sequence VALUES('template',9);
INSERT INTO sqlite_sequence VALUES('leaderboard',1);
CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name);
CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at);
CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at);
COMMIT;
